name: MACE_ORB_Distilled
seed: 2025
train_file: "./data/train.extxyz" 
valid_fraction: 0.01 
test_file: "./data/test.extxyz"
energy_key: REF_energy 
forces_key: REF_forces
E0s: "average" 
model: MACE
hidden_irreps: '128x0e + 128x1o'
num_interactions: 2 
r_max: 5.0
batch_size: 16
swa: false
max_num_epochs: 100
ema: true
ema_decay: 0.99
amsgrad: yes
default_dtype: "float32"
device: cuda
lr: 1e-3
weight_decay: 5e-6
num_radial_basis: 16
num_workers: 8
model_dir: ./models
checkpoints_dir: ./checkpoints
restart_latest: yes